name=M5Unit-RTC
version=0.0.2
author=M5Stack
maintainer=M5Stack
sentence=Library for M5Stack UNIT RTC using M5UnitUnified
paragraph=
category=Device Control
url=https://github.com/m5stack/M5Unit-RTC
architectures=esp32
includes=Unit_RTC.h, M5UnitUnifiedRTC.h
depends=M5UnitUnified,M5Utility,M5HAL
