;-----------------------------------------------------------------------
; M5Unit-RTC
; For examples (Using M5UnitUnified)
;-----------------------------------------------------------------------
[platformio]

[env]
build_flags =-Wall -Wextra -Wreturn-local-addr -Werror=format -Werror=return-local-addr
lib_ldf_mode = deep
test_framework = googletest
test_build_src = true
lib_deps=m5stack/M5Unified
  m5stack/M5UnitUnified@>=0.4.0

[m5base]
monitor_speed = 115200
monitor_filters = esp32_exception_decoder, time
upload_speed = 1500000
test_speed = 115200
test_ignore=  native/*

[Core]
extends = m5base
board = m5stack-core-esp32-16M
lib_deps = ${env.lib_deps}

[Core2]
extends = m5base
board = m5stack-core2
lib_deps = ${env.lib_deps}

[CoreS3]
extends = m5base
board = m5stack-cores3
lib_deps = ${env.lib_deps}

[Fire]
extends = m5base
board = m5stack-fire
lib_deps = ${env.lib_deps}

[StampS3]
;include M5Capsule, DinMeter
extends = m5base
board = m5stack-stamps3
lib_deps = ${env.lib_deps}

[Dial]
extends = m5base
board = m5stack-stamps3
lib_deps = ${env.lib_deps}
  m5stack/M5Dial

[Atom]
;include AtomMatrix,AtomLite,AtomU
extends = m5base
board = m5stack-atom
lib_deps = ${env.lib_deps}

[AtomS3]
;include AtomEchoS3R,AtomS3Lite,AtomS3U
extends = m5base
board = m5stack-atoms3
lib_deps = ${env.lib_deps}

; Using ./boards/m5stack-atoms3r.json
[AtomS3R]
;include AtomEchoS3R
extends = m5base
board = m5stack-atoms3r
lib_deps = ${env.lib_deps}

; Using ./boards/m5stack-nanoc6.json
[NanoC6]
extends = m5base
board = m5stack-nanoc6
lib_deps = ${env.lib_deps}
board_build.partitions = default.csv

[StickCPlus]
extends = m5base
board = m5stick-c
lib_deps = ${env.lib_deps}

; Using ./boards/m5stick-cplus2.json
[StickCPlus2]
extends = m5base
board = m5stick-cplus2
lib_deps = ${env.lib_deps}

[StickS3]
extends = m5base
board = esp32-s3-devkitc-1
board_build.arduino.partitions = default_8MB.csv
board_build.arduino.memory_type = qio_opi
build_flags =
    -DESP32S3
    -DBOARD_HAS_PSRAM
    -mfix-esp32-psram-cache-issue
    -DARDUINO_USB_CDC_ON_BOOT=1
    -DARDUINO_USB_MODE=1
lib_deps = ${env.lib_deps}

[Paper]
extends = m5base
board = m5stack-fire
lib_deps = ${env.lib_deps}

[CoreInk]
extends = m5base
board = m5stack-coreink
lib_deps = ${env.lib_deps}

[Cardputer]
extends = m5base
board = esp32-s3-devkitc-1
build_flags =
  -DESP32S3
  -DARDUINO_USB_CDC_ON_BOOT=1
  -DARDUINO_USB_MODE=1
lib_deps = ${env.lib_deps}

[Tab5]
extends = m5base
board = esp32-p4-evboard
board_build.mcu = esp32p4
board_build.flash_mode = qio
build_flags =
    -DBOARD_HAS_PSRAM
    -DARDUINO_USB_CDC_ON_BOOT=1
    -DARDUINO_USB_MODE=1
lib_deps = ${env.lib_deps}

[NessoN1]
extends = m5base
board = arduino_nesso_n1
lib_deps = ${env.lib_deps}

[sdl]
build_flags = -O3 -xc++ -std=c++14 -lSDL2
  -arch arm64                                ; for arm mac
  -I"/usr/local/include/SDL2"                ; for intel mac homebrew SDL2
  -L"/usr/local/lib"                         ; for intel mac homebrew SDL2
  -I"${sysenv.HOMEBREW_PREFIX}/include/SDL2" ; for arm mac homebrew SDL2
  -L"${sysenv.HOMEBREW_PREFIX}/lib"          ; for arm mac homebrew SDL2
platform = native
test_filter= native/*
test_ignore= embedded/*
lib_deps = ${env.lib_deps}

; --------------------------------
;Choose framework
[arduino_latest]
platform = espressif32 @ 6.12.0
framework = arduino

[nanoc6_latest]
platform = espressif32 @ 6.12.0
platform_packages =
	platformio/framework-arduinoespressif32 @ https://github.com/espressif/arduino-esp32.git#3.0.7
	platformio/framework-arduinoespressif32-libs @ https://github.com/espressif/esp32-arduino-libs.git#idf-release/v5.1
framework = arduino

[pioarduino_latest]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/55.03.36/platform-espressif32.zip
framework = arduino

; --------------------------------
;Choose build options
[option_release]
build_type=release
build_flags = ${env.build_flags}
  -DCORE_DEBUG_LEVEL=3
  -DLOG_LOCAL_LEVEL=3
  -DAPP_LOG_LEVEL=3
  -DM5_LOG_LEVEL=3

[option_log]
build_type=release
build_flags = ${env.build_flags}
  -DCORE_DEBUG_LEVEL=5
  -DLOG_LOCAL_LEVEL=5
  -DAPP_LOG_LEVEL=5

[option_debug]
build_type=debug
build_flags = ${env.build_flags}
  -DCORE_DEBUG_LEVEL=5
  -DLOG_LOCAL_LEVEL=5
  -DAPP_LOG_LEVEL=5
  -DDEBUG

[option_map]
build_type=release
build_flags = ${env.build_flags}
  -DCORE_DEBUG_LEVEL=3
  -DLOG_LOCAL_LEVEL=3
  -DAPP_LOG_LEVEL=3
  -DM5_LOG_LEVEL=0
  -Wl,-Map,output.map

; Require at leaset C++14 after 1.13.0
[test_fw]
lib_deps = google/googletest@1.12.1


;--------------------------------
;Tests
;--------------------------------
[env:test_UnitRTC_Core]
extends=Core, option_release, arduino_latest
lib_deps = ${Core.lib_deps}
  ${test_fw.lib_deps}
test_filter= embedded/test_pcf8563

[env:test_UnitRTC_Core2]
extends=Core2, option_release, arduino_latest
lib_deps = ${Core2.lib_deps}
  ${test_fw.lib_deps}
test_filter= embedded/test_pcf8563

[env:test_UnitRTC_CoreS3]
extends=CoreS3, option_release, arduino_latest
lib_deps = ${CoreS3.lib_deps}
  ${test_fw.lib_deps}
test_filter= embedded/test_pcf8563

[env:test_UnitRTC_Fire]
extends=Fire, option_release, arduino_latest
lib_deps = ${Fire.lib_deps}
  ${test_fw.lib_deps}
test_filter= embedded/test_pcf8563

[env:test_UnitRTC_StampS3]
extends=StampS3, option_release, arduino_latest
lib_deps = ${StampS3.lib_deps}
  ${test_fw.lib_deps}
test_filter= embedded/test_pcf8563

[env:test_UnitRTC_Dial]
extends=Dial, option_release, arduino_latest
lib_deps = ${Dial.lib_deps}
  ${test_fw.lib_deps}
test_filter= embedded/test_pcf8563

[env:test_UnitRTC_Atom]
extends=Atom, option_release, arduino_latest
lib_deps = ${Atom.lib_deps}
  ${test_fw.lib_deps}
test_filter= embedded/test_pcf8563

[env:test_UnitRTC_AtomS3]
extends=AtomS3, option_release, arduino_latest
lib_deps = ${AtomS3.lib_deps}
  ${test_fw.lib_deps}
test_filter= embedded/test_pcf8563

[env:test_UnitRTC_AtomS3R]
extends=AtomS3R, option_release, arduino_latest
lib_deps = ${AtomS3R.lib_deps}
  ${test_fw.lib_deps}
test_filter= embedded/test_pcf8563

[env:test_UnitRTC_NanoC6]
extends=NanoC6, option_release, nanoc6_latest
lib_deps = ${NanoC6.lib_deps}
  ${test_fw.lib_deps}
test_filter= embedded/test_pcf8563

[env:test_UnitRTC_StickCPlus]
extends=StickCPlus, option_release, arduino_latest
lib_deps = ${StickCPlus.lib_deps}
  ${test_fw.lib_deps}
test_filter= embedded/test_pcf8563

[env:test_UnitRTC_StickCPlus2]
extends=StickCPlus2, option_release, arduino_latest
lib_deps = ${StickCPlus2.lib_deps}
  ${test_fw.lib_deps}
test_filter= embedded/test_pcf8563

[env:test_UnitRTC_StickS3]
extends=StickS3, option_release, arduino_latest
build_flags = ${StickS3.build_flags}
  ${option_release.build_flags}
lib_deps = ${StickS3.lib_deps}
  ${test_fw.lib_deps}
test_filter= embedded/test_pcf8563

[env:test_UnitRTC_Paper]
extends=Paper, option_release, arduino_latest
lib_deps = ${Paper.lib_deps}
  ${test_fw.lib_deps}
test_filter= embedded/test_pcf8563

[env:test_UnitRTC_CoreInk]
extends=CoreInk, option_release, arduino_latest
lib_deps = ${CoreInk.lib_deps}
  ${test_fw.lib_deps}
test_filter= embedded/test_pcf8563

[env:test_UnitRTC_Cardputer]
extends=Cardputer, option_release, arduino_latest
build_flags = ${Cardputer.build_flags}
  ${option_release.build_flags}
lib_deps = ${Cardputer.lib_deps}
  ${test_fw.lib_deps}
test_filter= embedded/test_pcf8563

[env:test_UnitRTC_Tab5]
extends=Tab5, option_release, pioarduino_latest
build_flags = ${Tab5.build_flags}
  ${option_release.build_flags}
lib_deps = ${Tab5.lib_deps}
  ${test_fw.lib_deps}
test_filter= embedded/test_pcf8563

[env:test_UnitRTC_NessoN1]
extends=NessoN1, option_release, pioarduino_latest
lib_deps = ${NessoN1.lib_deps}
  ${test_fw.lib_deps}
test_filter= embedded/test_pcf8563

[env:test_native]
extends=sdl
lib_deps = ${sdl.lib_deps}
  ${test_fw.lib_deps}
test_filter= native/*


;--------------------------------
;Examples by M5UnitUnified
;--------------------------------
;--------------------------------
;UnitRTC (NTPSync)
;--------------------------------
[env:UnitRTC_NTPSync_Core_Arduino_latest]
extends=Core, option_release, arduino_latest
build_src_filter = +<*> -<.git/> -<.svn/> +<../examples/UnitUnified/UnitRTC/NTPSync>

[env:UnitRTC_NTPSync_Core2_Arduino_latest]
extends=Core2, option_release, arduino_latest
build_src_filter = +<*> -<.git/> -<.svn/> +<../examples/UnitUnified/UnitRTC/NTPSync>

[env:UnitRTC_NTPSync_CoreS3_Arduino_latest]
extends=CoreS3, option_release, arduino_latest
build_src_filter = +<*> -<.git/> -<.svn/> +<../examples/UnitUnified/UnitRTC/NTPSync>

[env:UnitRTC_NTPSync_StampS3_Arduino_latest]
extends=StampS3, option_release, arduino_latest
build_src_filter = +<*> -<.git/> -<.svn/> +<../examples/UnitUnified/UnitRTC/NTPSync>

[env:UnitRTC_NTPSync_Atom_Arduino_latest]
extends=Atom, option_release, arduino_latest
build_src_filter = +<*> -<.git/> -<.svn/> +<../examples/UnitUnified/UnitRTC/NTPSync>

[env:UnitRTC_NTPSync_AtomS3_Arduino_latest]
extends=AtomS3, option_release, arduino_latest
build_src_filter = +<*> -<.git/> -<.svn/> +<../examples/UnitUnified/UnitRTC/NTPSync>

[env:UnitRTC_NTPSync_AtomS3R_Arduino_latest]
extends=AtomS3R, option_release, arduino_latest
build_src_filter = +<*> -<.git/> -<.svn/> +<../examples/UnitUnified/UnitRTC/NTPSync>

[env:UnitRTC_NTPSync_Dial_Arduino_latest]
extends=Dial, option_release, arduino_latest
build_src_filter = +<*> -<.git/> -<.svn/> +<../examples/UnitUnified/UnitRTC/NTPSync>

[env:UnitRTC_NTPSync_NanoC6_Arduino_latest]
extends=NanoC6, option_release, nanoc6_latest
build_src_filter = +<*> -<.git/> -<.svn/> +<../examples/UnitUnified/UnitRTC/NTPSync>

[env:UnitRTC_NTPSync_StickCPlus_Arduino_latest]
extends=StickCPlus, option_release, arduino_latest
build_src_filter = +<*> -<.git/> -<.svn/> +<../examples/UnitUnified/UnitRTC/NTPSync>

[env:UnitRTC_NTPSync_StickCPlus2_Arduino_latest]
extends=StickCPlus2, option_release, arduino_latest
build_src_filter = +<*> -<.git/> -<.svn/> +<../examples/UnitUnified/UnitRTC/NTPSync>

[env:UnitRTC_NTPSync_StickS3_Arduino_latest]
extends=StickS3, option_release, arduino_latest
build_src_filter = +<*> -<.git/> -<.svn/> +<../examples/UnitUnified/UnitRTC/NTPSync>
build_flags = ${StickS3.build_flags}
  ${option_release.build_flags}

[env:UnitRTC_NTPSync_Paper_Arduino_latest]
extends=Paper, option_release, arduino_latest
build_src_filter = +<*> -<.git/> -<.svn/> +<../examples/UnitUnified/UnitRTC/NTPSync>

[env:UnitRTC_NTPSync_CoreInk_Arduino_latest]
extends=CoreInk, option_release, arduino_latest
build_src_filter = +<*> -<.git/> -<.svn/> +<../examples/UnitUnified/UnitRTC/NTPSync>

[env:UnitRTC_NTPSync_Fire_Arduino_latest]
extends=Fire, option_release, arduino_latest
build_src_filter = +<*> -<.git/> -<.svn/> +<../examples/UnitUnified/UnitRTC/NTPSync>

[env:UnitRTC_NTPSync_Cardputer_Arduino_latest]
extends=Cardputer, option_release, arduino_latest
build_src_filter = +<*> -<.git/> -<.svn/> +<../examples/UnitUnified/UnitRTC/NTPSync>
build_flags = ${Cardputer.build_flags}
  ${option_release.build_flags}

[env:UnitRTC_NTPSync_Tab5_Arduino_latest]
extends=Tab5, option_release, pioarduino_latest
build_src_filter = +<*> -<.git/> -<.svn/> +<../examples/UnitUnified/UnitRTC/NTPSync>
build_flags = ${Tab5.build_flags}
  ${option_release.build_flags}

[env:UnitRTC_NTPSync_NessoN1_Arduino_latest]
extends=NessoN1, option_release, pioarduino_latest
build_src_filter = +<*> -<.git/> -<.svn/> +<../examples/UnitUnified/UnitRTC/NTPSync>

;--------------------------------
;UnitRTC (AlarmNotify)
;--------------------------------
;
; For the following samples, please refer to NTPSync to create env for your own environment
; 以下のサンプルは、NTPSync を参考にして、自分の環境にあった env を作成してください
;
[env:UnitRTC_AlarmNotify_Core_Arduino_latest]
extends=Core, option_release, arduino_latest
build_src_filter = +<*> -<.git/> -<.svn/> +<../examples/UnitUnified/UnitRTC/AlarmNotify>

;--------------------------------
;UnitRTC (PeriodicTimer)
;--------------------------------
;
; For the following samples, please refer to NTPSync to create env for your own environment
; 以下のサンプルは、NTPSync を参考にして、自分の環境にあった env を作成してください
[env:UnitRTC_PeriodicTimer_Core_Arduino_latest]
extends=Core, option_release, arduino_latest
build_src_filter = +<*> -<.git/> -<.svn/> +<../examples/UnitUnified/UnitRTC/PeriodicTimer>


